export const all = [
  "Heating Element",
  "Cooling Element",
  "Chopping Element",
  "Dewdrop",
  "Crushed Pebble",
  "Wild Herb",
  "Ash Residue",
  "Moss Clump",
  "Steam Essence",
  "Mudstone Paste",
  "Leaf Slivers",
  "Charred Foliage",
  "Cinder Dust",
  "Silver Silk",
  "Foggy Moss",
  "Condensed Vapor",
  "Aether Clay",
  "River Stone",
  "Smoldering Fronds",
  "Ember Veil",
  "Ash Crystals",
  "Veil of Silence",
  "Mistwalker's Elixir",
  "Frostbreath Draught",
  "Skybound Tonic",
  "Earthshaper Elixir",
  "Inferno Tide Elixir",
  "Framefracture Brew",
  "Searing Chill Tonic",
  "Volcanic Draught",
];

export const initial = [
  "Heating Element",
  "Cooling Element",
  "Chopping Element",
  "Dewdrop",
  "Crushed Pebble",
  "Wild Herb",
  "Ash Residue",
  "Moss Clump",
  "Silver Silk",
  "River Stone",
];

export const recipes = [
  ["Steam Essence", ["Dewdrop", "Heating Element"]],
  ["Mudstone Paste", ["Dewdrop", "Crushed Pebble"]],
  ["Leaf Slivers", ["Wild Herb", "Chopping Element"]],
  ["Charred Foliage", ["Wild Herb", "Heating Element"]],
  ["Cinder Dust", ["Ash Residue", "Heating Element"]],
  ["Foggy Moss", ["Moss Clump", "Steam Essence"]],
  ["Condensed Vapor", ["Steam Essence", "Cooling Element"]],
  ["Aether Clay", ["Steam Essence", "Mudstone Paste"]],
  ["Smoldering Fronds", ["Leaf Slivers", "Charred Foliage"]],
  ["Ember Veil", ["Charred Foliage", "Cinder Dust"]],
  ["Ash Crystals", ["Cinder Dust", "Cooling Element"]],
  ["Veil of Silence", ["Silver Silk", "Foggy Moss"]],
  ["Mistwalker's Elixir", ["Foggy Moss", "Condensed Vapor"]],
  ["Frostbreath Draught", ["Condensed Vapor", "Cooling Element"]],
  ["Skybound Tonic", ["Condensed Vapor", "Aether Clay"]],
  ["Earthshaper Elixir", ["Aether Clay", "River Stone"]],
  ["Inferno Tide Elixir", ["River Stone", "Smoldering Fronds"]],
  ["Framefracture Brew", ["Ember Veil", "Heating Element"]],
  ["Searing Chill Tonic", ["Ember Veil", "Cooling Element"]],
  ["Volcanic Draught", ["Ash Crystals", "Heating Element"]],
];
