export const all = [
  "Heating Element",
  "Cooling Element",
  "Chopping Element",
  "Dewdrop",
  "Crushed Pebble",
  "Wild Herb",
  "Ash Residue",
  "Moss Clump",
  "Steam Essence",
  "Mudstone Paste",
  "Leaf Slivers",
  "Charred Foliage",
  "Cinder Dust",
  "Silver Silk",
  "Foggy Moss",
  "Condensed Vapor",
  "Aether Clay",
  "River Stone",
  "Smoldering Fronds",
  "Ember Veil",
  "Ash Crystals",
  "Veil of Silence",
  "Mistwalker's Elixir",
  "Frostbreath Draught",
  "Skybound Tonic",
  "Earthshaper Elixir",
  "Inferno Tide Elixir",
  "Framefracture Brew",
  "Searing Chill Tonic",
  "Volcanic Draught",
];

export const initial = [
  "Heating Element",
  "Cooling Element",
  "Chopping Element",
  "Dewdrop",
  "Crushed Pebble",
  "Wild Herb",
  "Ash Residue",
  "Moss Clump",
  "Silver Silk",
  "River Stone",
];

export const recipes = [
  ["Steam Essence", ["Dewdrop", "Heating Element"]],
  ["Mudstone Paste", ["Crushed Pebble", "Dewdrop"]],
  ["Leaf Slivers", ["Chopping Element", "Wild Herb"]],
  ["Charred Foliage", ["Heating Element", "Wild Herb"]],
  ["Cinder Dust", ["Ash Residue", "Heating Element"]],
  ["Foggy Moss", ["Moss Clump", "Steam Essence"]],
  ["Condensed Vapor", ["Cooling Element", "Steam Essence"]],
  ["Aether Clay", ["Mudstone Paste", "Steam Essence"]],
  ["Smoldering Fronds", ["Charred Foliage", "Leaf Slivers"]],
  ["Ember Veil", ["Charred Foliage", "Cinder Dust"]],
  ["Ash Crystals", ["Cinder Dust", "Cooling Element"]],
  ["Veil of Silence", ["Foggy Moss", "Silver Silk"]],
  ["Mistwalker's Elixir", ["Condensed Vapor", "Foggy Moss"]],
  ["Frostbreath Draught", ["Condensed Vapor", "Cooling Element"]],
  ["Skybound Tonic", ["Aether Clay", "Condensed Vapor"]],
  ["Earthshaper Elixir", ["Aether Clay", "River Stone"]],
  ["Inferno Tide Elixir", ["River Stone", "Smoldering Fronds"]],
  ["Framefracture Brew", ["Ember Veil", "Heating Element"]],
  ["Searing Chill Tonic", ["Cooling Element", "Ember Veil"]],
  ["Volcanic Draught", ["Ash Crystals", "Heating Element"]],
];

export const init_properties = {
  "Heating Element": ["Property1", "Property2", "Property3"],
  "Veil of Silence": ["Purple", "Hot", "Bubbling"],
  "Mistwalker's Elixir": ["Green", "Smoky", "Warm"],
  "Frostbreath Draught": [],
  "Skybound Tonic": [],
  "Earthshaper Elixir": [],
  "Inferno Tide Elixir": [],
  "Framefracture Brew": [],
  "Searing Chill Tonic": [],
  "Volcanic Draught": [],
}